# Copying in Immutable :


# Immutable- No change happens under the same id

In the below example; variable a,b are immutable. We can refer as immutable style of copying. 

Every time a new object is created, it will have a new memory address. Except when it is —
1. a very short string
2. an integer within [-5, 256]
3. an empty immutable containers (e.g. tuples)

In [14]:
a=10
id(a)

4543821232

In [15]:
b=a
id(b)

4543821232

In [16]:
a=5
print('a',id(a))
print('b',id(b))

a 4543821072
b 4543821232


10 is stored in the same id as saved initially.  

10 is immutable. That id will have 10 forever; it will not change (Immutable) . If the 'a' value changes, that will be stored in the new id. 

Where as in the list, if there is any change done; under the same id itself, the change happens. (Mutable)

Mutablitity means change;  change happening under the same id.


# Lists are mutable, strings are immutable 

# Python's Memory Management:

Links

1. http://foobarnbaz.com/2012/07/08/understanding-python-variables/
2. https://towardsdatascience.com/assignment-shallow-or-deep-a-story-about-pythons-memory-management-b8fad87bfa6c

Collections: https://towardsdatascience.com/pythons-collections-module-high-performance-container-data-types-cb4187afb5fc

Mutable things have two type of copying things:
1. Deep Copying
2. Shallow Cpoying

Shallow copy: New copied will have different id, but points to the same object

Deep copy: New copied will have different id and also different object gets created 

https://www.geeksforgeeks.org/copy-python-deep-copy-shallow-copy/

The difference between shallow and deep copying is only relevant for compound objects (objects that contain other objects, like lists or class instances):
- A shallow copy constructs a new compound object and then (to the extent possible) inserts references into it to the objects found in the original.
- A deep copy constructs a new compound object and then, recursively, inserts copies into it of the objects found in the original.

# Normal Copying, Deep Copying & Shallow Copying

In [76]:
a = [1,[10,11],3]
b=a
c = copy.copy(a)
d = copy.deepcopy(a)
print("a:",id(a),"ele:",id(a[0]),id(a[1]),id(a[2]))
print("b:",id(b),"ele:",id(b[0]),id(b[1]),id(b[2]))
print("c:",id(c),"ele:",id(c[0]),id(c[1]),id(c[2]))
print("d:",id(d),"ele:",id(d[0]),id(d[1]),id(d[2]))
a[1].append(20)
print(a)
print(b)
print(c)
print(d)
print("a:",id(a),"ele:",id(a[0]),id(a[1]),id(a[2]))
print("b:",id(b),"ele:",id(b[0]),id(b[1]),id(b[2]))
print("c:",id(c),"ele:",id(c[0]),id(c[1]),id(c[2]))
print("d:",id(d),"ele:",id(d[0]),id(d[1]),id(d[2]))

a: 4607105376 ele: 4543820944 4607452736 4543821008
b: 4607105376 ele: 4543820944 4607452736 4543821008
c: 4607104496 ele: 4543820944 4607452736 4543821008
d: 4607176288 ele: 4543820944 4607397792 4543821008
[1, [10, 11, 20], 3]
[1, [10, 11, 20], 3]
[1, [10, 11, 20], 3]
[1, [10, 11], 3]
a: 4607105376 ele: 4543820944 4607452736 4543821008
b: 4607105376 ele: 4543820944 4607452736 4543821008
c: 4607104496 ele: 4543820944 4607452736 4543821008
d: 4607176288 ele: 4543820944 4607397792 4543821008


# Why create a shallow copy of a list?

By normal copying if we change anything in b, also changes in a. So
inorder to avoid that we do shallow copying.

In [69]:
round1 = ['chuck norris', 'bruce lee', 'sonny chiba']
round2 = round1
round2.remove('sonny chiba')
print(round1) 
print(round2)

['chuck norris', 'bruce lee']
['chuck norris', 'bruce lee']


In [70]:
round1 = ['chuck norris', 'bruce lee', 'sonny chiba']
round3= round1.copy()
round3.remove('sonny chiba')
print(round1) 
print(round3)

['chuck norris', 'bruce lee', 'sonny chiba']
['chuck norris', 'bruce lee']


# Do python lists store values or pointers?

1. Python lists don't store any values themselves. They store pointers to the values stored elsewhere in memory. 
2. This allows lists to be mutable.

In [20]:
print(id(1))

4543820944


In [21]:
print(id(2))

4543820976


In [23]:
a=[1,2,3]
print(id(a))

4585367904


In [24]:
print(id(a[0]))

4543820944


In [25]:
print(id(a[1]))

4543820976


So, if we add any new element in the list, the id of the new element (pointer)
will add to the existing list. Thats why list is mutable. 

# Difference between List and Tuple:

1. Lists are mutable objects which means you can modify a list object after it has been created.

2. Tuples, on the other hand, are immutable objects which means you can’t modify a tuple object after it’s been created.

https://www.afternerd.com/blog/difference-between-list-tuple/

Tuple is more memory efficient

In [20]:
e=(1,2,3,4)
print(id(e))
f=e
print(id(f))

4433299696
4433299696


In [21]:
#e[0]=10
#print(e,id(e))
#print(f,id(f))

# Numpy array and List: 

1. Numpy array provides fast and efficient operations on arrays of homogeneous data.
2. Numpy array does element wise operations. List doesnot have this property. That's why we convert df columns into numpy arrays and do differences, sums.
3. Elements of an array are stored contiguous in memory. All rows in an array should have same number of columns.   
Where as list is not( list of list).
4. Python list is by default 1 dimensional. But we can create an N-Dimensional list. But then too it will be 1 D list storing another 1D list. 

https://www.geeksforgeeks.org/python-lists-vs-numpy-arrays/

Advantages of using Numpy Arrays Over Python Lists:

1. consumes less memory.
2. fast as compared to the python List.
3. convenient to use.

# Element wise operation in numpy 

In [13]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


# Element wise operation not performed in list 


In [15]:
l1=[1,2,3]
l2=[4,5,5]
l1+l2

[1, 2, 3, 4, 5, 5]

# Numpy Array

https://likegeeks.com/numpy-array-tutorial/

In [43]:
import numpy
a=numpy.array([1,2,3])
print(a)

[1 2 3]


In [48]:
a_1=numpy.append(a,[10,11,12])
print(a_1)
print(a)

[ 1  2  3 10 11 12]
[1 2 3]


In [58]:
b_1=numpy.array([[1,2,3],[4,5,6]])
b=numpy.array([[10],[11]])
a_2=numpy.append(b_1,b,axis=1)

print(a_2)

[[ 1  2  3 10]
 [ 4  5  6 11]]


# Hash Map

This is similar to an object in JavaScript and a dictionary in Python language. 

In this type of data structure, you give the hash map a word or a key and it retrieves the definition or the value for you. 

Under the hood it works a lot like an array. The key gets run through the function called the “hashing function” that spills out the memory location for you.

The way it’s different is that these memory locations need not be next to each other, rather can be anywhere. Therefore, there’s no issue with the increase in size.

However, there is a different problem — depending on the hashing algorithm you use, two keys could hash to the same memory location. 

This is what’s known as a “collision” and there are multiple ways to resolve them but again, it’s all happening under the hood.

Search in Hash Maps is O(1). [Dictionary, sets]

https://towardsdatascience.com/data-structures-simplified-and-classified-e0c1e304436b

# Dictionary

Keys are immutable, but the dictionary is mutable

Why keys cannot have list, but can be tuple, int, str?
As the dictionary keys are immutable, it cannot have mutable things. 

# Lambda

Lambda function is inline fucntion.

This function can have any number of arguments but only one expression, which is evaluated and returned.

Conceptually the lambda expression lambda x, y: x + y is the same as declaring a function with def, just written inline. The difference is I didn’t bind it to a name like add before I used it.


I simply stated the expression I wanted to compute and then immediately evaluated it by calling it like a regular function.

Lambda definition does not include a “return” statement, it always contains an expression which is returned. 
We can also put a lambda definition anywhere a function is expected, and we don’t have to assign it to a variable at all. 
This is the simplicity of lambda functions.

Filter, Map, Reduce using Lambda

# Map does only for single objects

In [13]:
list_ = [1,2,3,4]
print([x**2 for x in list_]) 
#this actually loads the complete list intiially and then iterates over

[1, 4, 9, 16]


In [14]:
print(list(map(lambda x : x**2 , list_)))
#this function takes one at a time, and performs the action. Memory efficient


[1, 4, 9, 16]


# Reduce 

Given a function, reduce iterates over a sequence and calls the function on every element. 
The output from the previous element is passed as an argument when calling the function on the next element.

In [81]:
import functools
list_ = [1,2,3,4]
#print([x**2 for x in list_])
#this actually loads the complete list intiially and then iterates over
#print(list(map(lambda x : x**2 , list_)))
print(functools.reduce(lambda x,y : x+y, list_))
#this takes two a time, and then calculates#memory efficient

#takes sum_ and the next element
def reduce_fn(list_):
    sum_ = 0
    for i in range(len(list_)):
        sum_ = sum_ + a[i]
    print(sum_) 

10


# Filter

In [17]:
list_=[1,2,3,4]
final_list = list(filter(lambda x: (x%2 != 0) , list_)) 

print(final_list)

[1, 3]


#Iterator and generators

https://www.programiz.com/python-programming/iterator
https://www.programiz.com/python-programming/generator
https://www.youtube.com/watch?v=bD05uGo_sVI

In [74]:
def gen_(list):
    my_iter = iter(list)
    #print(my_iter)
    yield next(my_iter)
    yield next(my_iter)
    yield next(my_iter)
    yield next(my_iter)

In [75]:
print(gen_([1,2,3,4]))

<generator object gen_ at 0x108010c50>


In [76]:
for item in gen_([1,2,3,4]):
    print(item)

1
2
3
4


In [82]:
def iter_(list):
    my_iter = iter(list)
    #print(my_iter)
    return next(my_iter)
    return next(my_iter)
    return next(my_iter)
    return next(my_iter)

In [83]:
iter_([1,2,3,4])

1

In [87]:
def iter_list_(list):
    my_iter = iter(list)
    i_l=[]
    for i in range(len(list)):
        i_l.append(next(my_iter))
    return i_l        
    

In [88]:
iter_list_([1,2,3,4])

[1, 2, 3, 4]

# Decorators

A function that takes another another funct as an arg, adds some kind of functionality and then return another function without changng
rhe soure functionality

# List Items 

1. Checking a list containing an element 

In [2]:
li=[1,2,3,'a','b','c']

In [3]:
'a' in li

True

2. Iterating over multiple lists at same time: 

In [4]:
name = ['Snowball', 'Chewy', 'Bubbles', 'Gruff']
animal = ['Cat', 'Dog', 'Fish', 'Goat']
age = [1, 2, 2, 6]

In [5]:
for a,b,c in zip(name,animal,age):
    print("%s likes %s at %s age"%(a,b,c))

Snowball likes Cat at 1 age
Chewy likes Dog at 2 age
Bubbles likes Fish at 2 age
Gruff likes Goat at 6 age


In [77]:
alphabet = ['a', 'b', 'c']
integers = [1, 2, 3]
list(zip(alphabet, integers))

[('a', 1), ('b', 2), ('c', 3)]

3. Append & Extend

In [18]:
a=[1,2,3,4]
b=[1,2,3,4]
a.append([5,6])
print("a",a)
b.extend([5,6])
print("b",b)


a [1, 2, 3, 4, [5, 6]]
b [1, 2, 3, 4, 5, 6]


4. Delete, Remove and pop

1.  Delete an element in the list by index
2. .remove() removes the first instance of a matching object. 
3. .pop() removes an object by its index.
4. By default, pop removes the last element from a list if an index isn’t specified.

In [56]:
a=['w', 'x', 'y', 'z']
del a[1]
print(a)
del a[:2]
print(a)

['w', 'y', 'z']
['z']


a = ['a', 'a', 'b', 'b', 'c', 'c']

In [45]:
a.remove('b')
a

['a', 'a', 'b', 'c', 'c']

In [46]:
a.pop(1)

'a'

In [47]:
a

['a', 'b', 'c', 'c']

5. Removing duplicate elements in a list

In [49]:
li=[1,3,3,4,5,2,7,7]
list(set(li))

[1, 2, 3, 4, 5, 7]

6. Find the index of the 1st matching element

In [51]:
fruit=['pear', 'orange', 'apple', 'grapefruit', 'apple', 'pear']
print(fruit.index('pear'))
print(fruit.index('orange'))

0
1


7. Remove all elements from a list

In [52]:
fruit = ['pear', 'orange', 'apple']
print(id(fruit))

4584314912


In [55]:
fruit.clear()
print(fruit)
print(id(fruit))


[]
4584314912


8. Iterate over both the values in a list and their indices

In [57]:
grocery_list = ['flour','cheese','carrots']


In [58]:
for i,v in enumerate(grocery_list):
    print("%s in %s"%(i,v))

0 in flour
1 in cheese
2 in carrots


9. Count the occurrence of a specific object in a list

In [62]:
pets = ['dog','cat','fish','fish','cat']
pets.count('fish')

2

10. Insert a value at specific index in an existing list

In [80]:
li = ['a','b','c','d','e']
li.insert(2, 'HERE')
li

['a', 'b', 'HERE', 'c', 'd', 'e']

11. List to Dictionaries using counter

In [82]:
from collections import Counter
li = ['blue', 'pink', 'green', 'green', 'yellow', 'pink', 'orange']
Counter(li)

Counter({'blue': 1, 'pink': 2, 'green': 2, 'yellow': 1, 'orange': 1})

12. Sort and Sorted

i) sort() modifies the list in place. 

ii) sorted() returns a new list in reverse order.

13. List as Stack 

Stack - LIFO

In [91]:
stack = []
stack.append('Jess')
stack.append('Todd')
stack.append('Yuan')
print(stack) ss
print(stack.pop()) #=> Yuan
print(stack) 

['Jess', 'Todd', 'Yuan']
Yuan
['Jess', 'Todd']


One benefit of a stack is that elements can be added and removed in O(1) time 
because the list does not need to be iterated over.